# Introduction

In this session, we see how to implement in Python the most fundamental matrix operation: matrix–matrix mutliplication. We will start in the most naive way and then work our way up to less straightforward but more efficient algorithms.

## Python packages
In this module, we will be using two very popular Python packages, [NumPy](https://numpy.org) and [SciPy](https://scipy.org/). Confusingly enough, they both contain a `linalg` submodule, and unfortunately there is an overlap in functionality between the two. For context, you can read the first two paragraphs of [the documentation of the NumPy `linalg` submodule](https://numpy.org/devdocs/reference/routines.linalg.html), wich reports some differences between the two. The [documentaion of the corresponding SciPy submodule](https://docs.scipy.org/doc/scipy/reference/linalg.html) may also be helpful later in the course.

For now, let's just import `numpy`.

In [1]:
import numpy as np

## Fundamentals of `numpy` arrays
Before implementing any matrix algorithm, we need to now how to generate and manipulate matrices. The `numpy` packages can help us with this.

First of all, let us generate some 2D `numpy` arrays from a list of elements. We can do this in two ways:

In [2]:
# A is a 2-by-4 matrix.
A = np.matrix('1 1 1 1; 1 2 3 4')

# B is a 4-by-3 matrix.
B = np.matrix([[1, 1, 1], [1, 2, 3], [1, 3, 5], [1, 4, 7]])

Note that the first method (used to construct `A`) is more compact than the former, and therefore may be preferable and less prone to errors, although you will rarely input a matrix element by element. Note that these two matrices are consistent, and their product is therefore well defined. We can compute it easily with built-in `numpy` command `@`.

There are several functions we can use to generate special matrices.

In [3]:
# O is a 2-by-3 matrix of zeros.
O = np.zeros([2, 3])

# E is a 3-by-2 matrix of ones.
E = np.zeros([3, 3])

# I is the 3-by-3 identity matrix, that is, a matrix with
# ones on the diagonal and zeros everywhere else.
I = np.eye(3)

We can now print these matrices to check that their entries are indeed what we expect.

In [4]:
print("O =\n", O)
print("\nE =\n", E)
print("\nI =\n", I)
print("\nA =\n", A)
print("\nB = \n", B)
print("\nAB = \n", A @ B)

O =
 [[0. 0. 0.]
 [0. 0. 0.]]

E =
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

I =
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

A =
 [[1 1 1 1]
 [1 2 3 4]]

B = 
 [[1 1 1]
 [1 2 3]
 [1 3 5]
 [1 4 7]]

AB = 
 [[ 4 10 16]
 [10 30 50]]


One of the most basic properties we might want to check are the dimensions (numbers of rows and column) of a matrix. The `numpy.ndim` function returns the number of dimensions of the attay, which will typically be 1 (for vectors) or 2 (for matrices) in this module. The `numpy.shape` function returns a tuple with the number of rows (and columns, for matrices) of `numpy` array. 

In [5]:
# Scalars have no dimensions, thus the shape tuple is empty.
print(np.ndim(1))
print(np.shape(1))

# Arrays have 1 dimension.
x = np.array([1, 2, 3])
print(x.ndim)
print(x.shape)

print(A.ndim)
print(A.shape)
print(np.shape(B))

0
()
1
(3,)
2
(2, 4)
(4, 3)


Another fundamental matrix operation we will be using is *transposition*. The transpose of the matrix $m \times n$ $A$ is the $n \times m$ matrix $B$ such that
$$
a_{ij} = b_{ji}.
$$
We denote the transpose of $A$ by $A^T$, and we can compute the transpose of a 2D `numpy` array with the `numpy.transpose` function.

In [6]:
print("A^T =\n", A.transpose())

A^T =
 [[1 1]
 [1 2]
 [1 3]
 [1 4]]


You can select a specific element of a `numpy` matrix using square brackets, as you would in Python lists. 

**REMEMBER:** Just as in Python lists, both dimensions of a matrix start from 0, **not** from 1.

For example the instructions to print $a_{24}$ and $b_{43}$ are

In [7]:
print(A[1, 3])
print(B[3, 2])

4
7


Often, rather than single elements we might want to take a submatrix. For example, we might want to extract a row, a column, or a block in a certain position. We can do this by using the *slicing* operator. The following examples extract the first row of $A$, the first column of $B$, and the top-left $2 \times 2$ block of $B$.

In [8]:
print("A_{1,*} = \n", A[1, :])
print("B_{*,1} = \n", B[:, 1])
print("B_{1-2,1-2}", B[1:2, 1:2])

A_{1,*} = 
 [[1 2 3 4]]
B_{*,1} = 
 [[1]
 [2]
 [3]
 [4]]
B_{1-2,1-2} [[2]]


Now we have all the ingredients we need to implement a function that computes the product of two 2D `numpy` arrays.

# Matrix–matrix multiplication
Let $A$ and $B$ be a $m \times p$ ($m$ rows and $p$ columns) and a $q \times n$ ($q$ rows and $n$ columns) matrix, respectively. If $p = q$, then $A$ and $B$ are said to be *conformable*, and their product $C = AB$ is an $m \times n$ matrix with elements

$$
c_{ij} = \sum_{k = 1}^{p} a_{ik}b_{kj}.
$$

### Naive algorithm
Our first task will be to write a function `compute_mxm_naive` that given in input two `numpy` arrays matrices `A` and `B` returns their product if the are conformable and raises an exception otherwise. Try to complete the function skeleton below. The code you write should have three nested loops, one over $i$, one over $j$, and one over $k$. Note that the order in which the three indices appear does not matter for the correctness of the algorithm.

In [9]:
"""Compute the product of two conformable matrices using the definition, or raise an exception."""
def compute_mxm_naive(A, B):
    # Check the dimensions of A and B, and raise an exception is A and B are not conformable.
    # The Python code to raise an exception is: raise Exception("<Exception message>")
    ### BEGIN SOLUTION
    (m, p) = A.shape
    (q, n) = B.shape
    if (p != q):
        raise Exception("Matrices are not conformable.")
    ### END SOLUTION
    
    # Initialize the matrix C, compute its elements using the formula above, and return it. 
    # BEGIN SOLUTION
    C = np.zeros([m, n])
    for i in range(m):
        for j in range(n):
            for k in range (p):
                C[i,j] += A[i,k] * B[k,j]
    return C
    ### END SOLUTION

We now want to test our function for correctness and performance, and to do so it will be convenient to have a function that generates test matrices of given dimension. We can generate an $m \times n$ matrix with random entries with the following one-line function, which constructs a 1D `numpy` array of lenght $mn$ and then reshapes it into an $m \times n$ matrix (that is, a 2D `numpy` array).

In [10]:
"""Generate an m-by-n matrix with random entries."""
def generate_matrix(m, n):
    return np.reshape(np.random.randn(m * n), [m, n])

First of all, let us look for obvious bugs in `compute_mxm_naive`. We will do that by comparing, on a selection of small matrices with different shapes, the matrices returned by `compute_mxm_naive` and by the built-in `@` function. To test for equality, we will use the `numpy.allclose` function, which is a better choice when dealing with matrices. 

In [11]:
"""Compare the matrix product computed by the function `f` and by the built-in operator `@`."""
def compare_accuracy_on_conformable_matrices(m, n, p, f):
    A = generate_matrix(m, p)
    B = generate_matrix(p, n)
    if np.allclose(f(A, B), A @ B):
        return True
    else:
        return False

"""
Run basic correctness test on the function `f`.
The latter should be a pointer to a function that takes two matrices and returns their product.
"""
def run_sanity_check(f):
    for m in range(1, 4):
        for n in range(1, 4):
            for p in range(1, 4):
                assert(compare_accuracy_on_conformable_matrices(m, n, p, f))

f = compute_mxm_naive
run_sanity_check(f)

Next, we want to assess the performance of our implementation. In order to do so, we should use matrices of moderately large size. Now we can use the generated matrices to time the function `compute_mxm_naive`. In the cell below, `%time` is a built-in "magic command", also known as a "Magic", which returns the CPU time and wall time of the following line of code. Although it is not recommended as a way to benchmark code, it can give you a crude estimate that should be enough for now.

In [12]:
m = 100
A = generate_matrix(m, m)
B = generate_matrix(m, m)
%time C = compute_mxm_naive(A, B)
%time C = A @ B

CPU times: user 910 ms, sys: 1.11 ms, total: 911 ms
Wall time: 910 ms
CPU times: user 16.3 ms, sys: 9.42 ms, total: 25.7 ms
Wall time: 1.79 ms


Your implementation `compute_mxm_naive` should be over two order of magnitudes slower than `@`. We will see how to improve this implementaiton in the remainder of this notebook.

## Algorithm using inner products 
The $m \times n$ matrix `A` is a column vector if $n = 1$, a row vector if $m = 1$, and a scalar if $m = n = 1$. In linear algebra, a vector is usually denoted by a lowercase letter, such as $u$ or $v$, and is generally assumed to be a column vector. The *inned product* of two vectors $u$ and $v$ of length $n$ is the scalar $u^T v = v^T u$. We can compute the dot product of two 2D `numpy` arrays with the `@` operator, if they are conformable, and we can compute the dot product of two 1D `numpy` vectors of the same length with the function `np.dot()`.

Our next task will be to write a function `compute_mxm_with_inner_products` that given in input two matrices `A` and `B` computes their product using inner products. The idea is to use the formula
$$
c_{ij} = A_{i,*} B_{*,j},
$$
where $A_{i,*}$ denotes the $i$th row of $A$ and $B_{*,j}$ denotes the $j$th column of $B$.

Once again, you have a function skeleton to fill in. You might want to have a look at the discussion above about slicing. The code you write should have only two nested loops, one over $i$ and one over $j$. You can assume that the two matrices are conformable this time.

In [13]:
"""Compute the product of two confomable matrices using inner products."""
def compute_mxm_with_inner_products(A, B):
    # Get the dimensions of C, initialize the matrix, compute its elements
    # using inner products, and return it. 
    # BEGIN SOLUTION
    (m, p) = A.shape
    (q, n) = B.shape
    C = np.zeros([m, n])
    for i in range(m):
        for j in range(n):
            C[i, j] += A[i, :] @ B[:, j]
    return C
    ### END SOLUTION

To look for obvious bugs, can run the suite of simple tests we defined above.

In [14]:
f = compute_mxm_with_inner_products
run_sanity_check(f)

Now we can compare the performance of `compute_mxm_naive` and `compute_with_mxm_inner_products` on some matrices. We need to keep `m` moderately low to keep the runtime manageable.

In [15]:
m = 100
A = generate_matrix(m, m)
B = generate_matrix(m, m)
%time C_naive = compute_mxm_naive(A, B)
%time C_inner_product = compute_mxm_with_inner_products(A, B)

CPU times: user 1.47 s, sys: 689 ms, total: 2.16 s
Wall time: 850 ms
CPU times: user 24.7 ms, sys: 0 ns, total: 24.7 ms
Wall time: 24.5 ms


The version using inner products should be **much** faster than the naive one. The reason for this is that whenever we call a function that performs a matrix computation (such as the function that computes the inner product product), instead of relying on slow python code we are calling a highly optimised routine that:
1. is written in a low-level language (typically Fortran/C with inline assembly); and
2. is tuned to the architecture of the machine you are using.
This suggests the following crucial rule of thumb.

**Rule of thumb.** To improve the performance of your Python implementations of linear algebra algorithms, try to replace **for** loops with calls to `numpy` functions that work directly on vectors and matrices.

## Algorithm using outer products
To conclude this gallery of implementations of algorithms for matrix–matrix multiplication, let us look at an operation that will allow us to implement a function featuring only one **for** loop: the *outer product*. Let $u$ and $v$ be two vectors of length $m$ and $n$, respectively. The $m \times n$ matrix $uv^T$ is the outer product of $u$ and $v$. Note that the $n \times m$ matrix $vu^T$ is also an outer product, but clearly $uv^T \neq vu^T$—in general, the two don't even have the same shape!

Our next task will be to write a function `compute_mxm_with_outer_products` that, given in input two matrices $A$ and $B$, computes $C = AB$ using outer products. The function will use the formula
$$
C = \sum_{k=1}^{p} A_{*,k} B_{k,*}.
$$
As usual, a function skeleton is given below. The code should have only one loop over $k$.

In [16]:
"""Compute the product of two confomable matrices using outer products."""
def compute_mxm_with_outer_products(A, B):
    # Get the dimensions of C, initialize the matrix, compute its elements
    # using inner products, and return it. 
    # BEGIN SOLUTION
    (m, p) = A.shape
    (q, n) = B.shape
    C = np.zeros([m, n])
    for k in range(p):
        C += A[:, k:k+1] @ B[k:k+1, :]
    return C
    ### END SOLUTION

We can now run our suite of simple tests.

In [17]:
f = compute_mxm_with_outer_products
run_sanity_check(f)

We can time this function against `compute_mxm_with_inner_products` to check that the performance has indeed improved. We can increase the value of $m$ if we remove `compute_mxm_naive`. The built-in `numpy` function `@` should still be over one order of magnitude faster than the fastest of our implementations. But at this point, this should not surprise you: that function does not feature any for loops!

In [18]:
m = 300
A = generate_matrix(m, m)
B = generate_matrix(m, m)
%time C_inner_product = compute_mxm_with_inner_products(A,B)
%time C_outer_product = compute_mxm_with_outer_products(A,B)
%time C_built_in = A @ B 

CPU times: user 215 ms, sys: 0 ns, total: 215 ms
Wall time: 215 ms
CPU times: user 92.7 ms, sys: 4.29 ms, total: 96.9 ms
Wall time: 96.2 ms
CPU times: user 164 ms, sys: 117 ms, total: 280 ms
Wall time: 11.5 ms
